//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int Id { get; set; }
        public int IdTorneo { get; set; }
        public int IdBlancas { get; set; }
        public int IdNegras { get; set; }
        public Nullable<int> EloBlanas { get; set; }
        public Nullable<int> EloNegras { get; set; }
        public Nullable<decimal> VarELOBlancas { get; set; }
        public Nullable<decimal> VarELONegras { get; set; }
        public string Resultado { get; set; }
        public Nullable<int> IdTipoRitmo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<bool> Evaluada { get; set; }
        public string PGN { get; set; }
    
        public virtual TipoRitmo TipoRitmo { get; set; }
        public virtual Torneo Torneo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
