//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipanteTorneo
    {
        public int Id { get; set; }
        public int IdTorneo { get; set; }
        public int IdUsuario { get; set; }
        public int InicialELO { get; set; }
        public string ObservacionesParcicipante { get; set; }
    
        public virtual Torneo Torneo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
